runtime: php74

handlers:
- url: /dist/css
  static_dir: dist/css

- url: /dist/js
  static_dir: dist/js

- url: /images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))

- url: /.*
  script: index.php
